PratoFioritoWeb/PratoFioritoWeb/Models/Difficulty.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PratoFioritoWeb.Models
{
    public class Difficulty
    {
        public int id { get; set; }

        [Required]
        [Range(1, 999)]
        public int width { get; set; }

        [Required]
        [Range(1, 999)]
        public int height { get; set; }
    }
}

PratoFioritoWeb/PratoFioritoWeb/Models/ErrorViewModel.cs
using System;

namespace PratoFioritoWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PratoFioritoWeb/PratoFioritoWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PratoFioritoWeb.Models;

namespace PratoFioritoWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PratoFioritoWeb/PratoFioritoWeb/Controllers/PratoFioritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PratoFioritoWeb.Models;

namespace PratoFioritoWeb.Controllers
{
    public class PratoFioritoController : Controller
    {
        public IActionResult Index(int difficulty)
        {
            Difficulty diff = new Difficulty();
            if (difficulty == 0)
            {
                diff.height = 5;
                diff.width = 7;
            }
            return View(diff);
        }
    }
}

PratoFioritoWeb/PratoFioritoWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a asp-controller="PratoFiorito" asp-action="Index" asp-difficulty="0">Prato Fiorito</a>
</div>

PratoFioritoWeb/PratoFioritoWeb/Views/PratoFiorito/Index.cshtml
@using PratoFioritoWeb.Models;

@model Difficulty

@{
    Random r = new Random();
    int type = r.Next(0, 2);
}

<div class="grid-container">
    @for (int h = 0; h < Model.height; h++)
    {
        @for (int w = 0; w < Model.width; w++)
        {
            <div class="grid-element" data-x="@h" data-y="@w" data-type="@r.Next(0, 2)"></div>
        }
    }
</div>

<br />
<div class="grid-element-bomb" style="height:100px;width:100px;">
</div>

<br />
<svg width="400" height="180">
    <rect x="50" y="20" rx="20" ry="20" width="150" height="150"
          style="fill:red;stroke:black;stroke-width:5;opacity:0.5" />
</svg>

@section Style {
    <link rel="stylesheet" href="~/img/bomb-thumbnail.png" />
}

@section Scripts{
    <script src="~/js/pratofiorito.js" type="text/javascript"></script> 
}

PratoFioritoWeb/PratoFioritoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PratoFioritoWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Style", required: false);
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PratoFioritoWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PratoFioritoWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>